In [20]:
# Pandas is used for data manipulation
import pandas as pd
# Read in data and display first 5 rows
df = pd.read_csv('C:/Users/shelb/OneDrive/Documents/MSA2021/Machine Learning/train.csv')
valid=pd.read_csv('C:/Users/shelb/OneDrive/Documents/MSA2021/Machine Learning/valid.csv')
test=pd.read_csv('C:/Users/shelb/OneDrive/Documents/MSA2021/Machine Learning/test.csv')
df.head(5)

,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,...,v121,v122,v123,v124,v125,v126,v127,cont.target,binary.target1,binary.target2
0,16.07,18.47,0.870060,-0.007407,-0.018315,-0.001862,False,-27.777778,59.714280,51.128020,...,92,-2,3173,2,94.15,-0.05,3696.0,0.130,0,0
1,16.07,18.46,0.870531,-0.011074,-0.018382,-0.006179,False,-23.529412,61.048270,51.168539,...,99,7,3175,2,94.16,0.01,3697.0,0.120,0,0
2,15.98,18.37,0.869897,-0.007435,-0.018382,-0.003731,False,-5.882353,64.812654,51.289999,...,100,1,3176,1,94.20,0.04,3698.0,0.090,0,0
3,15.96,18.37,0.868808,-0.012963,-0.016605,-0.009294,False,-41.176471,53.646082,51.035479,...,101,1,3176,0,94.20,0.00,3699.0,0.150,0,0
4,15.98,18.38,0.869423,-0.007407,-0.007407,-0.000373,False,-20.588235,58.173147,51.177162,...,95,-6,3176,0,94.20,0.00,3700.0,0.115,0,0

In [21]:
print('The shape of our features is:', df.shape)
print('The shape of our features is:', valid.shape)
print('The shape of our features is:', test.shape)

The shape of our features is: (250000, 130)
The shape of our features is: (100000, 130)
The shape of our features is: (85022, 127)

In [6]:
# Descriptive statistics for each column
df.describe()

,v1,v2,v3,v4,v5,v6,v8,v9,v10,v11,...,v121,v122,v123,v124,v125,v126,v127,cont.target,binary.target1,binary.target2
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,2.500000e+05,...,250000.000000,250000.000000,250000.000000,250000.00000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000
mean,15.097309,17.233371,0.865941,-0.000063,0.008618,0.084580,-48.202489,50.740589,50.581384,5.053187e+01,...,88.523164,-0.001168,3087.351820,-0.00056,91.855895,-0.000059,128695.500000,0.181078,0.130208,0.146444
std,4.203691,3.434529,0.071368,0.014809,0.396121,1.248967,30.545039,11.859037,2.864307,1.924337e+01,...,27.373283,8.157898,127.828622,100.77462,11.850937,0.285914,72168.927986,0.235931,0.336533,0.353551
min,8.850000,11.790000,0.692842,-0.171900,-0.280145,-0.346248,-100.000000,0.001838,26.638199,-1.136868e-13,...,5.000000,-69.000000,1.000000,-3253.00000,71.900000,-23.860000,3696.000000,-3.500004,0.000000,0.000000
25%,12.310000,15.040000,0.816012,-0.004935,-0.013528,-0.061254,-75.000000,42.879188,48.797683,3.615309e+01,...,72.000000,-4.000000,3045.000000,0.00000,83.680000,-0.080000,66195.750000,0.058000,0.000000,0.000000
50%,13.990000,16.470000,0.848044,0.000000,-0.001916,-0.017765,-46.883232,51.026543,50.717339,5.063554e+01,...,86.000000,0.000000,3101.000000,0.00000,88.750000,0.000000,128695.500000,0.135000,0.000000,0.000000
75%,16.500000,18.660000,0.903171,0.004405,0.010070,0.031439,-20.403030,58.734404,52.467659,6.491080e+01,...,102.000000,4.000000,3166.000000,1.00000,96.420000,0.080000,191195.250000,0.260000,0.000000,0.000000
max,53.290000,39.500000,1.474136,0.715751,22.345395,23.943773,0.000000,99.398521,60.999145,1.000000e+02,...,352.000000,269.000000,3265.000000,2722.00000,212.220000,74.350000,253695.000000,11.890000,1.000000,1.000000

In [22]:
cleanup_nums = {"v45":     {'Monday':0, 'Tuesday':1, 'Wednesday':2, 'Thursday':3, 'Friday':4}}
df.replace(cleanup_nums, inplace=True)
valid.replace(cleanup_nums, inplace=True)
test.replace(cleanup_nums, inplace=True)

In [24]:
# Use numpy to convert to arrays
import numpy as np
# Labels are the values we want to predict
y = np.array(df['cont.target'])
y_valid = np.array(valid['cont.target'])
# Remove the labels from the features
# axis 1 refers to the columns
x= df.drop(['cont.target','binary.target1','binary.target2','v7'], axis = 1)
x_valid= valid.drop(['cont.target','binary.target1','binary.target2','v7'], axis = 1)
x_test= test.drop(['v7'], axis = 1)
# Saving feature names for later use
#feature_list = list(features.columns)
# Convert to numpy array
x = np.array(x)
x_valid = np.array(x_valid)
x_test = np.array(x_test)

In [25]:
print('Training Features Shape:', x.shape)
print('Training Labels Shape:', y.shape)
print('Testing Features Shape:', x_valid.shape)
print('Testing Labels Shape:', y_valid.shape)

Training Features Shape: (250000, 126)
Training Labels Shape: (250000,)
Testing Features Shape: (100000, 126)
Testing Labels Shape: (100000,)

In [ ]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(x, y);

In [ ]:
# Use the forest's predict method on the test data
predictions = rf.predict(x_valid)
# Calculate the absolute errors
errors = abs(predictions - y_valid)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')
Mean Absolute Error: 3.83 degrees.

In [ ]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_valid)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')
Accuracy: 93.99 %.